//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.03 at 03:44:54 PM CEST 
//


package com.meandmyphone.genericdevicefancyvator.core.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scene_properties" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="background" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}background" minOccurs="0"/>
 *                   &lt;element name="on_click" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}on_click" minOccurs="0"/>
 *                   &lt;element name="camera" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}camera" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sprite" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}sprite" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sceneProperties",
    "sprite"
})
@XmlRootElement(name = "scene")
public class Scene {

    @XmlElement(name = "scene_properties")
    protected Scene.SceneProperties sceneProperties;
    protected List<Sprite> sprite;

    /**
     * Gets the value of the sceneProperties property.
     * 
     * @return
     *     possible object is
     *     {@link Scene.SceneProperties }
     *     
     */
    public Scene.SceneProperties getSceneProperties() {
        return sceneProperties;
    }

    /**
     * Sets the value of the sceneProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scene.SceneProperties }
     *     
     */
    public void setSceneProperties(Scene.SceneProperties value) {
        this.sceneProperties = value;
    }

    /**
     * Gets the value of the sprite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sprite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSprite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sprite }
     * 
     * 
     */
    public List<Sprite> getSprite() {
        if (sprite == null) {
            sprite = new ArrayList<Sprite>();
        }
        return this.sprite;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="background" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}background" minOccurs="0"/>
     *         &lt;element name="on_click" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}on_click" minOccurs="0"/>
     *         &lt;element name="camera" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}camera" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "background",
        "onClick",
        "camera"
    })
    public static class SceneProperties {

        protected Background background;
        @XmlElement(name = "on_click")
        protected OnClick onClick;
        protected Camera camera;

        /**
         * Gets the value of the background property.
         * 
         * @return
         *     possible object is
         *     {@link Background }
         *     
         */
        public Background getBackground() {
            return background;
        }

        /**
         * Sets the value of the background property.
         * 
         * @param value
         *     allowed object is
         *     {@link Background }
         *     
         */
        public void setBackground(Background value) {
            this.background = value;
        }

        /**
         * Gets the value of the onClick property.
         * 
         * @return
         *     possible object is
         *     {@link OnClick }
         *     
         */
        public OnClick getOnClick() {
            return onClick;
        }

        /**
         * Sets the value of the onClick property.
         * 
         * @param value
         *     allowed object is
         *     {@link OnClick }
         *     
         */
        public void setOnClick(OnClick value) {
            this.onClick = value;
        }

        /**
         * Gets the value of the camera property.
         * 
         * @return
         *     possible object is
         *     {@link Camera }
         *     
         */
        public Camera getCamera() {
            return camera;
        }

        /**
         * Sets the value of the camera property.
         * 
         * @param value
         *     allowed object is
         *     {@link Camera }
         *     
         */
        public void setCamera(Camera value) {
            this.camera = value;
        }

    }

}
