//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.03 at 06:00:00 PM CEST 
//


package com.meandmyphone.genericdevicefancyvator.xml.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ease.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ease">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="linear"/>
 *     &lt;enumeration value="cubic_in"/>
 *     &lt;enumeration value="cubic_out"/>
 *     &lt;enumeration value="cubic_inout"/>
 *     &lt;enumeration value="quad_in"/>
 *     &lt;enumeration value="quad_out"/>
 *     &lt;enumeration value="quad_inout"/>
 *     &lt;enumeration value="sine_in"/>
 *     &lt;enumeration value="sine_out"/>
 *     &lt;enumeration value="sine_inout"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ease")
@XmlEnum
public enum Ease {

    @XmlEnumValue("linear")
    LINEAR("linear"),
    @XmlEnumValue("cubic_in")
    CUBIC_IN("cubic_in"),
    @XmlEnumValue("cubic_out")
    CUBIC_OUT("cubic_out"),
    @XmlEnumValue("cubic_inout")
    CUBIC_INOUT("cubic_inout"),
    @XmlEnumValue("quad_in")
    QUAD_IN("quad_in"),
    @XmlEnumValue("quad_out")
    QUAD_OUT("quad_out"),
    @XmlEnumValue("quad_inout")
    QUAD_INOUT("quad_inout"),
    @XmlEnumValue("sine_in")
    SINE_IN("sine_in"),
    @XmlEnumValue("sine_out")
    SINE_OUT("sine_out"),
    @XmlEnumValue("sine_inout")
    SINE_INOUT("sine_inout");
    private final String value;

    Ease(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Ease fromValue(String v) {
        for (Ease c: Ease.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
