//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 09:08:53 PM CEST 
//


package com.meandmyphone.genericdevicefancyvator.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fade_transition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fade_transition">
 *   &lt;complexContent>
 *     &lt;extension base="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}transition">
 *       &lt;sequence>
 *         &lt;element name="from_alpha" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="to_alpha" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fade_transition", propOrder = {
    "fromAlpha",
    "toAlpha"
})
public class FadeTransition
    extends Transition
{

    @XmlElement(name = "from_alpha")
    protected float fromAlpha;
    @XmlElement(name = "to_alpha")
    protected float toAlpha;

    /**
     * Gets the value of the fromAlpha property.
     * 
     */
    public float getFromAlpha() {
        return fromAlpha;
    }

    /**
     * Sets the value of the fromAlpha property.
     * 
     */
    public void setFromAlpha(float value) {
        this.fromAlpha = value;
    }

    /**
     * Gets the value of the toAlpha property.
     * 
     */
    public float getToAlpha() {
        return toAlpha;
    }

    /**
     * Sets the value of the toAlpha property.
     * 
     */
    public void setToAlpha(float value) {
        this.toAlpha = value;
    }

}
