//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 09:08:53 PM CEST 
//


package com.meandmyphone.genericdevicefancyvator.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for position complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="position">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="sprite_relative_position" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}sprite_relative_position"/>
 *         &lt;element name="scene_relative_position" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}scene_relative_position"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "position", propOrder = {
    "spriteRelativePosition",
    "sceneRelativePosition"
})
public class Position {

    @XmlElement(name = "sprite_relative_position")
    protected SpriteRelativePosition spriteRelativePosition;
    @XmlElement(name = "scene_relative_position")
    protected SceneRelativePosition sceneRelativePosition;

    /**
     * Gets the value of the spriteRelativePosition property.
     * 
     * @return
     *     possible object is
     *     {@link SpriteRelativePosition }
     *     
     */
    public SpriteRelativePosition getSpriteRelativePosition() {
        return spriteRelativePosition;
    }

    /**
     * Sets the value of the spriteRelativePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpriteRelativePosition }
     *     
     */
    public void setSpriteRelativePosition(SpriteRelativePosition value) {
        this.spriteRelativePosition = value;
    }

    /**
     * Gets the value of the sceneRelativePosition property.
     * 
     * @return
     *     possible object is
     *     {@link SceneRelativePosition }
     *     
     */
    public SceneRelativePosition getSceneRelativePosition() {
        return sceneRelativePosition;
    }

    /**
     * Sets the value of the sceneRelativePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SceneRelativePosition }
     *     
     */
    public void setSceneRelativePosition(SceneRelativePosition value) {
        this.sceneRelativePosition = value;
    }

}
