//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.03 at 08:33:33 PM CEST 
//


package com.meandmyphone.genericdevicefancyvator.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rotate_transition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rotate_transition">
 *   &lt;complexContent>
 *     &lt;extension base="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}transition">
 *       &lt;sequence>
 *         &lt;element name="from_angle" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="to_angle" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rotate_transition", propOrder = {
    "fromAngle",
    "toAngle"
})
public class RotateTransition
    extends Transition
{

    @XmlElement(name = "from_angle")
    protected double fromAngle;
    @XmlElement(name = "to_angle")
    protected double toAngle;

    /**
     * Gets the value of the fromAngle property.
     * 
     */
    public double getFromAngle() {
        return fromAngle;
    }

    /**
     * Sets the value of the fromAngle property.
     * 
     */
    public void setFromAngle(double value) {
        this.fromAngle = value;
    }

    /**
     * Gets the value of the toAngle property.
     * 
     */
    public double getToAngle() {
        return toAngle;
    }

    /**
     * Sets the value of the toAngle property.
     * 
     */
    public void setToAngle(double value) {
        this.toAngle = value;
    }

}
