//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.07 at 09:01:16 PM CEST 
//


package com.meandmyphone.genericdevicefancyvator.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scene_relative_position complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="scene_relative_position">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scene_point" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}pivot"/>
 *         &lt;element name="x_distance_from_pivot" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}measure"/>
 *         &lt;element name="y_distance_from_pivot" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}measure"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scene_relative_position", propOrder = {
    "scenePoint",
    "xDistanceFromPivot",
    "yDistanceFromPivot"
})
public class SceneRelativePosition {

    @XmlElement(name = "scene_point", required = true)
    @XmlSchemaType(name = "string")
    protected Pivot scenePoint;
    @XmlElement(name = "x_distance_from_pivot", required = true)
    protected Measure xDistanceFromPivot;
    @XmlElement(name = "y_distance_from_pivot", required = true)
    protected Measure yDistanceFromPivot;

    /**
     * Gets the value of the scenePoint property.
     * 
     * @return
     *     possible object is
     *     {@link Pivot }
     *     
     */
    public Pivot getScenePoint() {
        return scenePoint;
    }

    /**
     * Sets the value of the scenePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pivot }
     *     
     */
    public void setScenePoint(Pivot value) {
        this.scenePoint = value;
    }

    /**
     * Gets the value of the xDistanceFromPivot property.
     * 
     * @return
     *     possible object is
     *     {@link Measure }
     *     
     */
    public Measure getXDistanceFromPivot() {
        return xDistanceFromPivot;
    }

    /**
     * Sets the value of the xDistanceFromPivot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Measure }
     *     
     */
    public void setXDistanceFromPivot(Measure value) {
        this.xDistanceFromPivot = value;
    }

    /**
     * Gets the value of the yDistanceFromPivot property.
     * 
     * @return
     *     possible object is
     *     {@link Measure }
     *     
     */
    public Measure getYDistanceFromPivot() {
        return yDistanceFromPivot;
    }

    /**
     * Sets the value of the yDistanceFromPivot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Measure }
     *     
     */
    public void setYDistanceFromPivot(Measure value) {
        this.yDistanceFromPivot = value;
    }

}
