//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 09:08:53 PM CEST 
//


package com.meandmyphone.genericdevicefancyvator.xml.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sprite complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sprite">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sprite_topleft_u" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="sprite_topleft_v" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="sprite_botright_u" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="sprite_botright_v" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="sprite_transform" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}sprite_transform"/>
 *         &lt;element name="alpha" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="scaleX" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="scaleY" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="rotation" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="pivot" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}pivot"/>
 *         &lt;element name="transition" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="fade_transition" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}fade_transition"/>
 *                   &lt;element name="translate_transition" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}translate_transition"/>
 *                   &lt;element name="rotate_transition" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}rotate_transition"/>
 *                   &lt;element name="scale_transition" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}scale_transition"/>
 *                   &lt;element name="flipbook_transition" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}flipbook_transition"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sprite", propOrder = {
    "id",
    "resource",
    "spriteTopleftU",
    "spriteTopleftV",
    "spriteBotrightU",
    "spriteBotrightV",
    "spriteTransform",
    "alpha",
    "scaleX",
    "scaleY",
    "rotation",
    "pivot",
    "transition"
})
@XmlSeeAlso({
    ImageBackground.class
})
public class Sprite {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String resource;
    @XmlElement(name = "sprite_topleft_u")
    protected float spriteTopleftU;
    @XmlElement(name = "sprite_topleft_v")
    protected float spriteTopleftV;
    @XmlElement(name = "sprite_botright_u")
    protected float spriteBotrightU;
    @XmlElement(name = "sprite_botright_v")
    protected float spriteBotrightV;
    @XmlElement(name = "sprite_transform", required = true)
    protected SpriteTransform spriteTransform;
    protected float alpha;
    @XmlElement(defaultValue = "1")
    protected float scaleX;
    @XmlElement(defaultValue = "1")
    protected float scaleY;
    @XmlElement(defaultValue = "0")
    protected float rotation;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Pivot pivot;
    protected List<Sprite.Transition> transition;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the resource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResource() {
        return resource;
    }

    /**
     * Sets the value of the resource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResource(String value) {
        this.resource = value;
    }

    /**
     * Gets the value of the spriteTopleftU property.
     * 
     */
    public float getSpriteTopleftU() {
        return spriteTopleftU;
    }

    /**
     * Sets the value of the spriteTopleftU property.
     * 
     */
    public void setSpriteTopleftU(float value) {
        this.spriteTopleftU = value;
    }

    /**
     * Gets the value of the spriteTopleftV property.
     * 
     */
    public float getSpriteTopleftV() {
        return spriteTopleftV;
    }

    /**
     * Sets the value of the spriteTopleftV property.
     * 
     */
    public void setSpriteTopleftV(float value) {
        this.spriteTopleftV = value;
    }

    /**
     * Gets the value of the spriteBotrightU property.
     * 
     */
    public float getSpriteBotrightU() {
        return spriteBotrightU;
    }

    /**
     * Sets the value of the spriteBotrightU property.
     * 
     */
    public void setSpriteBotrightU(float value) {
        this.spriteBotrightU = value;
    }

    /**
     * Gets the value of the spriteBotrightV property.
     * 
     */
    public float getSpriteBotrightV() {
        return spriteBotrightV;
    }

    /**
     * Sets the value of the spriteBotrightV property.
     * 
     */
    public void setSpriteBotrightV(float value) {
        this.spriteBotrightV = value;
    }

    /**
     * Gets the value of the spriteTransform property.
     * 
     * @return
     *     possible object is
     *     {@link SpriteTransform }
     *     
     */
    public SpriteTransform getSpriteTransform() {
        return spriteTransform;
    }

    /**
     * Sets the value of the spriteTransform property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpriteTransform }
     *     
     */
    public void setSpriteTransform(SpriteTransform value) {
        this.spriteTransform = value;
    }

    /**
     * Gets the value of the alpha property.
     * 
     */
    public float getAlpha() {
        return alpha;
    }

    /**
     * Sets the value of the alpha property.
     * 
     */
    public void setAlpha(float value) {
        this.alpha = value;
    }

    /**
     * Gets the value of the scaleX property.
     * 
     */
    public float getScaleX() {
        return scaleX;
    }

    /**
     * Sets the value of the scaleX property.
     * 
     */
    public void setScaleX(float value) {
        this.scaleX = value;
    }

    /**
     * Gets the value of the scaleY property.
     * 
     */
    public float getScaleY() {
        return scaleY;
    }

    /**
     * Sets the value of the scaleY property.
     * 
     */
    public void setScaleY(float value) {
        this.scaleY = value;
    }

    /**
     * Gets the value of the rotation property.
     * 
     */
    public float getRotation() {
        return rotation;
    }

    /**
     * Sets the value of the rotation property.
     * 
     */
    public void setRotation(float value) {
        this.rotation = value;
    }

    /**
     * Gets the value of the pivot property.
     * 
     * @return
     *     possible object is
     *     {@link Pivot }
     *     
     */
    public Pivot getPivot() {
        return pivot;
    }

    /**
     * Sets the value of the pivot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pivot }
     *     
     */
    public void setPivot(Pivot value) {
        this.pivot = value;
    }

    /**
     * Gets the value of the transition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sprite.Transition }
     * 
     * 
     */
    public List<Sprite.Transition> getTransition() {
        if (transition == null) {
            transition = new ArrayList<Sprite.Transition>();
        }
        return this.transition;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="fade_transition" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}fade_transition"/>
     *         &lt;element name="translate_transition" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}translate_transition"/>
     *         &lt;element name="rotate_transition" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}rotate_transition"/>
     *         &lt;element name="scale_transition" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}scale_transition"/>
     *         &lt;element name="flipbook_transition" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}flipbook_transition"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fadeTransition",
        "translateTransition",
        "rotateTransition",
        "scaleTransition",
        "flipbookTransition"
    })
    public static class Transition {

        @XmlElement(name = "fade_transition")
        protected FadeTransition fadeTransition;
        @XmlElement(name = "translate_transition")
        protected TranslateTransition translateTransition;
        @XmlElement(name = "rotate_transition")
        protected RotateTransition rotateTransition;
        @XmlElement(name = "scale_transition")
        protected ScaleTransition scaleTransition;
        @XmlElement(name = "flipbook_transition")
        protected FlipbookTransition flipbookTransition;

        /**
         * Gets the value of the fadeTransition property.
         * 
         * @return
         *     possible object is
         *     {@link FadeTransition }
         *     
         */
        public FadeTransition getFadeTransition() {
            return fadeTransition;
        }

        /**
         * Sets the value of the fadeTransition property.
         * 
         * @param value
         *     allowed object is
         *     {@link FadeTransition }
         *     
         */
        public void setFadeTransition(FadeTransition value) {
            this.fadeTransition = value;
        }

        /**
         * Gets the value of the translateTransition property.
         * 
         * @return
         *     possible object is
         *     {@link TranslateTransition }
         *     
         */
        public TranslateTransition getTranslateTransition() {
            return translateTransition;
        }

        /**
         * Sets the value of the translateTransition property.
         * 
         * @param value
         *     allowed object is
         *     {@link TranslateTransition }
         *     
         */
        public void setTranslateTransition(TranslateTransition value) {
            this.translateTransition = value;
        }

        /**
         * Gets the value of the rotateTransition property.
         * 
         * @return
         *     possible object is
         *     {@link RotateTransition }
         *     
         */
        public RotateTransition getRotateTransition() {
            return rotateTransition;
        }

        /**
         * Sets the value of the rotateTransition property.
         * 
         * @param value
         *     allowed object is
         *     {@link RotateTransition }
         *     
         */
        public void setRotateTransition(RotateTransition value) {
            this.rotateTransition = value;
        }

        /**
         * Gets the value of the scaleTransition property.
         * 
         * @return
         *     possible object is
         *     {@link ScaleTransition }
         *     
         */
        public ScaleTransition getScaleTransition() {
            return scaleTransition;
        }

        /**
         * Sets the value of the scaleTransition property.
         * 
         * @param value
         *     allowed object is
         *     {@link ScaleTransition }
         *     
         */
        public void setScaleTransition(ScaleTransition value) {
            this.scaleTransition = value;
        }

        /**
         * Gets the value of the flipbookTransition property.
         * 
         * @return
         *     possible object is
         *     {@link FlipbookTransition }
         *     
         */
        public FlipbookTransition getFlipbookTransition() {
            return flipbookTransition;
        }

        /**
         * Sets the value of the flipbookTransition property.
         * 
         * @param value
         *     allowed object is
         *     {@link FlipbookTransition }
         *     
         */
        public void setFlipbookTransition(FlipbookTransition value) {
            this.flipbookTransition = value;
        }

    }

}
