//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.07 at 09:01:16 PM CEST 
//


package com.meandmyphone.genericdevicefancyvator.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="ease" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}ease" default="linear" />
 *       &lt;attribute name="cycle_type" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}cycle_type" default="restart" />
 *       &lt;attribute name="cycle_count" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transition")
@XmlSeeAlso({
    FlipbookTransition.class,
    ScaleTransition.class,
    FadeTransition.class,
    TranslateTransition.class,
    RotateTransition.class
})
public class Transition {

    @XmlAttribute(name = "duration", required = true)
    protected int duration;
    @XmlAttribute(name = "ease")
    protected Ease ease;
    @XmlAttribute(name = "cycle_type")
    protected CycleType cycleType;
    @XmlAttribute(name = "cycle_count", required = true)
    protected int cycleCount;

    /**
     * Gets the value of the duration property.
     * 
     */
    public int getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     */
    public void setDuration(int value) {
        this.duration = value;
    }

    /**
     * Gets the value of the ease property.
     * 
     * @return
     *     possible object is
     *     {@link Ease }
     *     
     */
    public Ease getEase() {
        if (ease == null) {
            return Ease.LINEAR;
        } else {
            return ease;
        }
    }

    /**
     * Sets the value of the ease property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ease }
     *     
     */
    public void setEase(Ease value) {
        this.ease = value;
    }

    /**
     * Gets the value of the cycleType property.
     * 
     * @return
     *     possible object is
     *     {@link CycleType }
     *     
     */
    public CycleType getCycleType() {
        if (cycleType == null) {
            return CycleType.RESTART;
        } else {
            return cycleType;
        }
    }

    /**
     * Sets the value of the cycleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CycleType }
     *     
     */
    public void setCycleType(CycleType value) {
        this.cycleType = value;
    }

    /**
     * Gets the value of the cycleCount property.
     * 
     */
    public int getCycleCount() {
        return cycleCount;
    }

    /**
     * Sets the value of the cycleCount property.
     * 
     */
    public void setCycleCount(int value) {
        this.cycleCount = value;
    }

}
