//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.04 at 08:10:56 PM CEST 
//


package com.meandmyphone.genericdevicefancyvator.xml.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transition_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="transition_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="fade"/>
 *     &lt;enumeration value="rotate"/>
 *     &lt;enumeration value="scale"/>
 *     &lt;enumeration value="translate"/>
 *     &lt;enumeration value="flipbook"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "transition_type")
@XmlEnum
public enum TransitionType {

    @XmlEnumValue("fade")
    FADE("fade"),
    @XmlEnumValue("rotate")
    ROTATE("rotate"),
    @XmlEnumValue("scale")
    SCALE("scale"),
    @XmlEnumValue("translate")
    TRANSLATE("translate"),
    @XmlEnumValue("flipbook")
    FLIPBOOK("flipbook");
    private final String value;

    TransitionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransitionType fromValue(String v) {
        for (TransitionType c: TransitionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
