//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.08 at 09:08:53 PM CEST 
//


package com.meandmyphone.genericdevicefancyvator.xml.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for translate_transition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="translate_transition">
 *   &lt;complexContent>
 *     &lt;extension base="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}transition">
 *       &lt;sequence>
 *         &lt;element name="by_x" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}measure"/>
 *         &lt;element name="by_y" type="{https://github.com/csumpakabra/GenericDeviceFancyvator/blob/master/app/src/main/schemas/GDFScene.xsd}measure"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "translate_transition", propOrder = {
    "byX",
    "byY"
})
public class TranslateTransition
    extends Transition
{

    @XmlElement(name = "by_x", required = true)
    protected Measure byX;
    @XmlElement(name = "by_y", required = true)
    protected Measure byY;

    /**
     * Gets the value of the byX property.
     * 
     * @return
     *     possible object is
     *     {@link Measure }
     *     
     */
    public Measure getByX() {
        return byX;
    }

    /**
     * Sets the value of the byX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Measure }
     *     
     */
    public void setByX(Measure value) {
        this.byX = value;
    }

    /**
     * Gets the value of the byY property.
     * 
     * @return
     *     possible object is
     *     {@link Measure }
     *     
     */
    public Measure getByY() {
        return byY;
    }

    /**
     * Sets the value of the byY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Measure }
     *     
     */
    public void setByY(Measure value) {
        this.byY = value;
    }

}
